spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    database: mysql
    url: jdbc:mysql://127.0.0.1:3306/project
    username: root
    password: root123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-authentication
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
token:
  signing:
    #This key is used as base to generate tokens for authentication
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
  config:
    activate:
      on-profile: prod
